package org.fenixedu.bennu.user.management;

import org.fenixedu.bennu.core.domain.User;

import pt.ist.fenixframework.Atomic;
import pt.ist.fenixframework.Atomic.TxMode;

public class UserManager {

    /**
     * Creates a new user.
     * 
     * The user's username is generated by the configured {@link UsernameGenerator}. The given parameter is passed to the
     * generator to provide additional context to the user, allowing for further customization of the username.
     * 
     * @param parameter
     *            The parameter to pass to the {@link UsernameGenerator}
     * @return
     *         The newly created user.
     */
    @Atomic(mode = TxMode.WRITE)
    public static <T> User createDynamicUser(T parameter) {
        String username = UsernameGenerator.generate(parameter);
        return new User(username);
    }
}
